numero1 = int(input("Digite um número inteiro: "))
numero2 = int(input("Digite outro número inteiro: "))
numero3 = float(input("Digite um numero real: "))
print("o produto do dobro do primeiro com metade do segundo é igual a: ", (numero1 * 2) * numero2 /2)
print("a soma do triplo do primeiro com o terceiro é igual a: ", (numero1 * 3) + numero3)
print("O terceiro elevado ao cubo é igual a: ",numero3**3)